"use client";

import { Tabs } from "radix-ui";
import { useState } from "react";
import styles from "./CodeTabs.module.css";

export interface CodeFile {
  path: string;
  note: string;
  raw: string;
  /** Pre-highlighted at build time. */
  html: string;
}

/**
 * File switcher and copy button.
 *
 * The only client-side part of the code viewer. Radix Tabs supplies roving
 * focus and the correct tab/tabpanel wiring; the highlighted markup arrives
 * already rendered from the server.
 */
export function CodeTabs({ files }: { files: CodeFile[] }) {
  const [active, setActive] = useState(files[0]?.path ?? "");

  if (files.length === 0) return null;

  return (
    <Tabs.Root value={active} onValueChange={setActive} className={styles.root}>
      <div className={styles.bar}>
        <Tabs.List className={styles.list} aria-label="Source files">
          {files.map((file) => (
            <Tabs.Trigger
              key={file.path}
              value={file.path}
              className={styles.trigger}
            >
              {basename(file.path)}
            </Tabs.Trigger>
          ))}
        </Tabs.List>

        <CopyButton
          text={files.find((file) => file.path === active)?.raw ?? ""}
        />
      </div>

      {files.map((file) => (
        <Tabs.Content key={file.path} value={file.path} className={styles.content}>
          <p className={styles.note}>
            <code className={styles.path}>{file.path}</code>
            <span className={styles.dash}>—</span>
            {file.note}
          </p>

          {/* Markup is generated by shiki at build time from files in this
              repository, so there is no untrusted input in this HTML. */}
          <div
            className={styles.code}
            dangerouslySetInnerHTML={{ __html: file.html }}
          />
        </Tabs.Content>
      ))}
    </Tabs.Root>
  );
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  async function copy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch {
      // Clipboard access can be denied; leaving the label unchanged is a
      // truthful outcome, and the text is selectable regardless.
    }
  }

  return (
    <button type="button" className={styles.copy} onClick={copy}>
      {copied ? "Copied" : "Copy"}
      {/* Announced politely so the confirmation reaches screen readers,
          which would otherwise get no feedback from the label swap. */}
      <span className="srOnly" role="status">
        {copied ? "Copied to clipboard" : ""}
      </span>
    </button>
  );
}

function basename(path: string): string {
  return path.split("/").pop() ?? path;
}
